---
- name: Install consul client
  hosts: consul-client
  gather_facts: yes
  become: yes
  tasks:
    - name: include vars
      ansible.builtin.include_vars:
        file: vars.yml

    - name: Include install task file
      ansible.builtin.include_role:
        name: consul