---
- name: Install consul client
  hosts: consul-client
  gather_facts: yes
  become: yes
  vars:
    consul_datacenter: fabos
    consul_domain: fabos
    consul_servers_list: "{{ groups['consul-server'] | map('extract', hostvars, ['ansible_host']) + ['192.168.1.1'] }}"
  tasks:
    - name: include vars
      ansible.builtin.include_vars:
        file: vars.yml

    - name: Include install task file
      ansible.builtin.include_role:
        name: consul