---
- name: Get consul server IPs
  hosts: localhost
  connection: local
  gather_facts: no
  become: no
  tasks:
    - debug:
        var: groups['consul-server']

- name: Install consul client
  hosts: consul-client
  gather_facts: yes
  become: yes
  vars:
    consul_datacenter: fabos
    consul_domain: fabos
    consul_servers_list: "{{ groups['consul-server'] | map('extract', hostvars, ['ansible_host']) }}"
  tasks:
    - name: Include install task file
      ansible.builtin.include_role:
        name: consul