---
- name: Install consul server
  hosts: consul-server
  become: yes
  gather_facts: yes
  tasks:
    - name: Get Consul Server IP
      ansible.builtin.set_fact:
        consul_server_address: "{{ hostvars[groups['consul-server'] | first].ansible_host }}"

    - name: "Start consul-server via Docker Compose"
      community.docker.docker_compose:
        state: "present"
        project_name: "consul-server"
        definition: "{{ lookup('template', './docker-compose-consul-server.yml.j2') | from_yaml }}"
      register: docker_compose
      retries: 5
      delay: 5
      until: docker_compose.failed == false

    - name: Wait for consul-server port
      ansible.builtin.wait_for:
        port: 8500
        delay: 5