---
- name: Set server availability dict
  ansible.builtin.set_fact:
    server_availability: {}

- name: Check ports of server are available
  ansible.builtin.include_tasks: check_server_ports.yml
  loop: "{{ consul_servers_list }}"
  vars:
    server_ip: "{{ item }}"

- name: Show server availability
  ansible.builtin.debug:
    var: server_availability

- name: Set is_server_available
  ansible.builtin.set_fact:
    is_server_available: "{{ true in server_availability.values() }}"