---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: ubuntu1804-consul-client
    template_name: ubuntu-18-04
    groups: ['ssh', 'consul-client']
  - name: ubuntu1804-consul-server
    template_name: ubuntu-18-04-docker
    groups: ['ssh', 'consul-server']
provisioner:
  name: ansible
  playbooks:
    create: ../default/create.yml
    destroy: ../default/destroy.yml

    prepare: ../default-uninstall/prepare.yml
    converge: ../default-uninstall/converge.yml
    verify: ../default-uninstall/verify.yml
verifier:
  name: ansible
