---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: ubuntu2204-consul-client
    template_name: ubuntu-22-04
    groups: ['ssh', 'consul-client']
provisioner:
  name: ansible
  playbooks:
    create: ../default/create.yml
    destroy: ../default/destroy.yml
    converge: converge.yml
    verify: verify.yml
verifier:
  name: ansible
