---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: centos8-consul-client
    template_name: centos-stream-8
    groups: ['ssh', 'consul-client']
  - name: centos8-consul-server
    template_name: centos-stream-8-docker
    groups: ['ssh', 'consul-server']
provisioner:
  name: ansible
  playbooks:
    create: ../default/create.yml
    destroy: ../default/destroy.yml
    prepare: ../default-install/prepare.yml
    converge: ../default-install/converge.yml
    verify: ../default-install/verify.yml
verifier:
  name: ansible
