---
- name: Restore service
  hosts: consul-client
  gather_facts: yes
  become: yes
  vars:
    consul_datacenter: fabos
    consul_domain: fabos
    consul_servers_list: "{{ groups['consul-server'] | map('extract', hostvars, ['ansible_host']) + ['192.168.1.1'] }}"
    service:
      Address: ''
      Connect: {}
      CreateIndex: 24
      EnableTagOverride: false
      ID: 79d331c2-fbc9-48a2-b2a0-223f0c795ca3
      Meta:
        service-2-key1: service-2-value1
        service-2-key2: service-2-value2
        service-2-key3: service-2-value3
      ModifyIndex: 24
      PeerName: ''
      Proxy:
        Expose: {}
        MeshGateway: {}
        Mode: ''
      Service: Test-Service-2
      Tags:
      - service-2-tag1
      - service-2-tag2
      - service-2-tag3
      Weights:
        Passing: 1
        Warning: 1
  tasks:
    - name: Include restore_service task file
      ansible.builtin.include_tasks: ../../tasks/helper/restore_service.yml